permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Plugin directories
plugins_dir: _plugins

# Sitemap configuration
sitemap:
  exclude:
    - "/maptest/"
    - "/script/"
    - "/vendor/"
    - "/resume/"
    - "/en/resume/"
    - "*.json"
    - "*.xml"
    - "*.pdf"
    - "/blog/pub-crawling-in-istanbul-with-tsp/"
    - "/blog/vibe-coding-a-chrome-extension/"

# Site configuration
url: "https://blog.atr0p.dev"

# Multilingual configuration
languages: ["tr", "en"]
default_lang: "tr"
exclude_from_localization: ["i", "fonts", "f", "style.css", "sw.js", "maptest", "script", "vendor", "_site"]

# Collections configuration
collections:
  projects:
    output: true
    permalink: /:collection/:name/

exclude:
  - "vendor"
  - "maptest"
  - "script"
  - "resume/cv.pdf"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      starred: false
      music: false
      geo: false
      hidden: false
  -
    scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
      hidden: false            