permalink: /:categories/:title/
markdown: kramdown
plugins:
  - jekyll-redirect-from

# Collections configuration
collections:
  projects:
    output: true
    permalink: /:collection/:name/

exclude:
  - "vendor"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      starred: "false"
      music: "false"
  -
    scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"            