define({
    settings: "Ayarlar",
    addSearch: "Arama Katmanı Ekle",
    updateSearch: "Arama Katmanını Güncelle",
    addBuffer: "Varsayılan Tampon Ekle",
    updateBuffer: "Varsayılan Tampon",
    addSearchExpr: "Bir İfade Ekle",
    updateSearchExpr: "İfadeyi Güncelle",
    addExpressionValue: "İfade Değeri Ekle",
    updateExpressionValue: "İfade Değerini Güncelle",
    addExpression: "İfade Ekle",
    addLink: "Bağlantı Ekle",
    addRelate: "İlişki Ekle",
    availableRelates: "Mevcut İlişkiler",
    choose: "Seç",
    updateLink: "Bağlantıyı Güncelle",
    updateRelate: "İlişkiyi Güncelle",
    searchTitle: "Arama Başlığı",
    expressionsTitle: "Arama İfadeleri",
    linksTitle: "Arama Bağlantıları",
    relatesTitle: "Arama İlişkileri",
    bufferUnitTitle: "Tampon Birimleri",
    spatialRelationshipTitle: "Mekansal İlişkiler",
    linkAlias: "Bağlantı Takma Adı",
    relateAlias: "İlişki Takma Adı",
    disablenulllink: "Bağlantıyı Null Durumunda Devre Dışı Bırak",
    disablelinkinpopup: "PopUp'ta Bağlantıyı Devre Dışı Bırak",
    popuplinktype: "Bağlantı Türü",
    linktext: "Metin",
    linkimage: "Resim",
    linkiconcontent: "Bağlantı Simge İçeriği",
    linkcontent: "Bağlantı İçeriği",
    linkiconcontenthint: "Bağlantı simge içeriği geçerli bir URL\\simge resmine giden yol oluşturacak metin, alanlar veya her ikisinin bir kombinasyonu olabilir. Alan eklemek için metin alanının sağındaki mavi artı düğmesine tıklayın.",
    linkcontenthint: "Bağlantı içeriği geçerli bir URL\\bağlantılı öğeye giden yol oluşturacak metin, alanlar veya her ikisinin bir kombinasyonu olabilir. Alan eklemek için metin alanının sağındaki mavi artı düğmesine tıklayın.",
    valuesTitle: "Arama İfade Değerleri",
    actions: "Eylemler",
    zoomScale: "Yakınlaştırma Ölçeği",
    back: "Geri",
    sum: "Bu alanın değerlerini topla",
    sumlabel: "Toplam Etiketi",
    searchUrl: "Arama URL'si",
    browse: "Gözat",
    title: "Başlık",
    definitionexpr: "Tanım İfadesi",
    expression: "İfade",
    searchLabel: "Arama Etiketi",
    searchHint: "Arama İpucu",
    availableFields: "Mevcut Alanlar",
    name: "Ad",
    alias: "Takma Ad",
    includedFields: "Dahil Edilen Alanlar",
    cancel: "İptal",
    ok: "Tamam",
    addSearch2: "Arama Ekle",
    operationalLayerTip: "Sonucu İşletim Katmanı Olarak Ekle",
    initialView: "İlk Görünüm",
    disableTabs: "Düzenleme Devre Dışı Sekmeler",
    selectFeatures: "Şekle Göre",
    selectByAttribute: "Özniteliklere Göre",
    editDefaultSym: "Varsayılan Arama Sembolojisi",
    editDefaultBuffer: "Varsayılan Tampon Özelliklerini Düzenle",
    editDefaultGraphical: "Grafik Arama Seçeneklerini Düzenle",
    point: "İşaretçi Varsayılan Sembolü",
    line: "Çizgi Varsayılan Sembolü",
    poly: "Poligon Varsayılan Sembolü",
    includeall: "Hepsini Dahil Et",
    include: "Dahil Et",
    useMultiGraphics: "Çok parçalı grafiklerin varsayılan olarak etkinleştirilmesini sağlayın",
    addTolerance: "Nokta seçimine arama toleransı eklemeyi varsayılan olarak işaretle",
    keepGraphicalEnabled: "Her çizimden sonra grafik arama aracını etkin tut",
    autoZoom: "Arama sonuçlarına otomatik yakınlaştır",
    pointTolerance: "Grafiksel bir nokta aramasına eklenecek tolerans",
    searchExpressions: "Arama İfadeleri",
    expressionAlias: "İfade Takma Adı",
    addValue: "İfade Değeri Ekle",
    valuePrompt: "İstem",
    valueSQL: "SQL İfadesi",
    valueDefault: "Varsayılan Değer",
    textSearchHint: "Arama İpucu (Değer Örneği)",
    none: "Hiçbiri",
    string: "Dize",
    number: "Sayı",
    date: "Tarih",
    stringOperatorIn: "içinde", // örn. <stringFieldName> in ('California', 'Arizona')
    stringOperatorIs: "eşittir", // örn. <stringFieldName> is 'California'
    stringOperatorIsNot: "eşit değil",
    stringOperatorStartsWith: "ile başlar",
    stringOperatorEndsWith: "ile biter",
    stringOperatorContains: "içerir",
    stringOperatorDoesNotContain: "içermez",
    stringOperatorIsBlank: "boş",
    stringOperatorIsNotBlank: "boş değil",
    dateOperatorIsOn: "üzerinde", // örn. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "üzerinde değil",
    dateOperatorIsBefore: "öncesinde",
    dateOperatorIsAfter: "sonrasında",
    dateOperatorIsBeforeOrOn: "öncesinde veya üzerinde",
    dateOperatorIsAfterOrOn: "sonrasında veya üzerinde",
    dateOperatorDays: "günler",
    dateOperatorWeeks: "haftalar", // örn. <dateFieldName> son 4 haftada
    dateOperatorMonths: "aylar",
    dateOperatorInTheLast: "son",
    dateOperatorNotInTheLast: "son değil",
    dateOperatorIsBetween: "arasında",
    dateOperatorIsNotBetween: "arasında değil",
    dateOperatorIsBlank: "boş",
    dateOperatorIsNotBlank: "boş değil",
    numberOperatorIn: "içinde", // örn. <stringFieldName> in (1000,2000)
    numberOperatorIs: "eşittir", // örn. <numberFieldName> is 1000
    numberOperatorIsNot: "eşit değil",
    numberOperatorIsAtLeast: "en az",
    numberOperatorIsLessThan: "daha az",
    numberOperatorIsAtMost: "en çok",
    numberOperatorIsGreaterThan: "daha büyük",
    numberOperatorIsBetween: "arasında",
    numberOperatorIsNotBetween: "arasında değil",
    numberOperatorIsBlank: "boş",
    numberOperatorIsNotBlank: "boş değil",
    valueField: "Alan",
    valueOperation: "Operasyon",
    valueMethod: "Yöntem",
    all: "Hepsi",
    any: "Herhangi biri",
    value: "Değer",
    field: "Alan",
    unique: "Benzersiz",
    and: "ve",
    operator: "Operatör",
    valueTooltip: "Değer girin",
    fieldTooltip: "Mevcut alanlardan seçin",
    uniqueValueTooltip: "Seçili alandaki benzersiz değerleri seçin",
    friendlyDatePattern: "GG/AA/YYYY",
    askForValues: "Değerleri iste",
    prompt: "İstem",
    hint: "İpucu",
    strMatchMsgPart1: "Katmandaki özellikleri alın ",
    strMatchMsgPart2: " bu ve önceki ifade kriterlerine uyan",
    userListMsg: "Önceden tanımlanmış listeden değerleri iste",
    predefinedValue: "Önceden Tanımlanmış Değerler",
    predefinedLabel: "Önceden Tanımlanmış Etiketler",
    list: "Liste:",
    addListValue: "Liste Değeri Ekle",
    predefinedTooltip: "Önceden tanımlanmış değerler listesinden seçin",
    predefined: "Önceden Tanımlanmış",
    error: {
      invalidParams: "Geçersiz parametreler.",
      invalidUrl: "Geçersiz URL.",
      noFilterFields: "Katmanda filtre için kullanılabilecek alan yok.",
      invalidSQL: "Geçersiz SQL ifadesi.",
      cantParseSQL: "SQL ifadesi çözümlenemiyor."
    },
    edit: "Alan biçimini düzenle",
    dateformat: "Tarih formatı",
    dayShortMonthYear: "Gün kısa Ay Yıl",
    longDate: "Uzun Tarih",
    longMonthDayYear: "Uzun Ay Gün Yıl",
    longMonthYear: "Uzun Ay Yıl",
    shortDate: "Kısa Tarih",
    shortDateLongTime: "Kısa Gün Uzun Zaman",
    shortDateLongTime24: "Kısa Gün Uzun Zaman 24",
    shortDateShortTime: "Kısa Tarih Kısa Zaman",
    shortDateShortTime24: "Kısa Gün Kısa Zaman 24",
    shortMonthYear: "Kısa Ay Yıl",
    year: "Yıl",
    custom: "Özel",
    useutc: "UTC kullan",
    currencyfield: "Para Birimi Alanı",
    currencySymbol: "Para Birimi Simgesi",
    examplecurrency: "$",
    precision: "Kesinlik",
    exampleprecision: ".",
    usethousandssep: "Binlik ayırıcı kullan",
    examplethousands: ",",
    overrideSQL: "Geçersiz Kıl",
    editBufferUnit: "Tampon Birimleri Ekle veya Kaldır",
    defaultBufferValue: "Varsayılan Tampon Değeri",
    defaultBufferWKID: "Varsayılan Tampon Mekansal Referans WKID",
    bufferSymbol: "Tampon Sembolü (düzenlemek için sembole tıklayın)",
    addbufferunit: "Tampon Birimleri",
    addspatalrelationships: "Mevcut Mekansal İlişkiler",
    addUnit: "Birim Ekle\\Kaldır",
    addRemove: "Ekle\\Kaldır",
    warning: "Seçili Tampon Birimi Yok",
    addSymbol: "Katmana Özel Sembol Ekle\\Düzenle",
    pointSymbol: "Nokta Sembolü: ",
    lineSymbol: "Çizgi Sembolü: ",
    polySymbol: "Poligon Sembolü: ",
    symbologyTooltip: "Düzenlemek istediğiniz sembolojiyi sembole tıklayarak düzenleyin.",
    spatialSearchLayer: "Mekansal Arama Katmanı",
    editDefaultSpatial: "Mekansal Arama Özelliklerini Düzenle",
    layerSymbology: "Katman Sembolojisi",
    symbolServer: "Sunucudan",
    symbolConfig: "Varsayılanlardan",
    symbolLayer: "Katmandan",
    requiredfield: "Alan Gerekli",
    isempty: "Boş",
    showinattributetable: "Öznitelik Tablosu Widget'ında Otomatik Olarak Aç",
    showattachments: "Ekleri Göster",
    andor: "veya",
    tobeenabled: "etkinleştirilmek için",
    graphicalSearchOptions: "Grafik Arama Seçenekleri",
    addgraphicalsearchoptions: "Grafik Arama Seçenekleri",
    editdisabledtaboptions: "Devre Dışı Arama Sekmelerini Düzenle",
    graphictab: "Grafik Arama Sekmesi",
    attributetab: "Öznitelik Arama Sekmesi",
    spatialtab: "Mekansal Arama Sekmesi",
    resultstab: "Sonuçlar Sekmesi",
    availabletabs: "Devre Dışı Sekmeler",
    popuponly: "Yalnızca PopUp",
    graphicInteract: "Fareyle üzerine gelindiğinde arama grafiğinde açılır pencereyi göster",
    limit2mapextent: "Sonuçları varsayılan olarak haritanın kapsamıyla sınırlama",
    addbuffertolegend: "Tampon katmanını haritanın lejantına ekle",
    enableExportSearchURL: "Arama URL'sini dışa aktarmayı etkinleştir",
    uniqueValues: "Benzersiz değerler getiriliyor",
    processingUnique: "Benzersiz değerler işleniyor: ",
    of: " / ",
    showResultsPopup: "Sonuç kaydına tıklandığında açılır pencereyi göster",
    resultItemSorting: "Sonuç Öğesi Sıralama",
    configureFieldsTip: "Sorgu sonucunun sıralanacağı alanları lütfen yapılandırın.",
    addNew: "Yeni Ekle",
    sortingOrder: "Sıra",
    ascending: "Artan",
    descending: "Azalan",
    sortBy: "Sıralama Kriteri",
    thenBy: "Ardından",
    sortDisabledMsg: "Devre Dışı: Servis katmanı Gelişmiş Sorgu Yeteneklerini desteklemeli: OrderBy",
    editSortBy: "Sıralama Kriterini Düzenle",
    showuseMultiGraphics: "Çok parçalı grafiklerin etkinleştirilme seçeneğini göster",
    showaddTolerance: "Nokta seçimine arama toleransı ekleme seçeneğini göster",
    showaddsqltext: "Seçim kriterlerine metin sorgusu ekleme seçeneğini göster",
    showbuffergraphic: "Tampon Grafik seçeneklerini göster",
    buffergraphicbydefault: "Varsayılan olarak Tampon Grafik'i etkinleştir",
    expressionValueRequired: "Arama için bir değer girilmesi gerekmektedir",
    enableelocateselect: "eLocate Widget Grafikler",
    defExprPlaceholder: "İsteğe bağlı (widget yardımına bakın)",
    zoomscaletip: "Yakınlaştırma ölçeği tüm geometrik türlere uygulanacaktır, sadece noktalara değil",
    forceScale: "Ölçeği Zorla",
    editResultFormat: "Sonuç Biçimlendirme",
    formatTooltip: "Burada ayarlanan biçimlendirme, sonuç açılır pencerelerini ve widget sonuç metnini etkileyecektir",
    attribTitleLbl: "Sonuç Öznitelik Başlığı:",
    attribTitleExample: "Ad",
    attribValueLbl: "Sonuç Öznitelik Değeri:",
    attribValueExample: "John Doe",
    color: "Renk",
    insertbold: "Kalın",
    insertitalic: "İtalik",
    insertunderline: "Altı Çizili",
    preview: "Biçim Önizleme",
    maxBufferValue: "Maksimum tampon mesafesi",
    disablePopups: "Arama sonuçları açılır penceresini devre dışı bırak",
    disableUVCache: "Benzersiz Değerler Önbelleğini Devre Dışı Bırak (widget yardımına bakın)",
    resultWrap: "Sonuç metnini sar",
    resultDefaultMsg: "Varsayılan olarak her öznitelik için tüm metin ve başlığı tek satırda görünür ve uzun metni görmek için kaydırma yaparsınız.",
    usePopupFrom: "Açılır Pencereyi Kullan",
    popupWebmap: "Web Haritası",
    popupeSearch: "eSearch",
    usePopupFrom2: "bu katman için",
    popupWebmapTip: "Katmanın web haritasında tanımlı bir açılır penceresi yoksa, standart eSearch açılır penceresi kullanılacaktır",
    dropdownfilter: "Açılır menüleri filtrele",
    contains: "İçerir",
    begins: "İle başlar",
    allowcsvexport: "CSV İhracat",
    allowgeoexport: "GeoJSON İhracat",
    allowfcexport: "Özellik Koleksiyonu İhracat",
    startdateminus: "Başlangıç Tarihi şu andan itibaren eksi",
    days: "gün(ler)",
    statistics: "İstatistiklerden Çıkar",
    defaultactivetool: "Varsayılan olarak etkinleştirilen grafik aracı",
    globalOverrides: "Genel Ayarları Geçersiz Kıl",
    hidenulldata: "Widget sonuçlarında ve açılır pencerelerde Boş verileri gizle",
    autoZoomBuffer: "Tampon sonuçlarına otomatik yakınlaştır",
    editGeneral: "Genel Ayarları Düzenle",
    editGeneraloptions: "Genel Widget Seçenekleri",
    zoomFactor: "Yakınlaştırma Faktörü",
    zoomFactorNote: "Örneğin, 1.5 değeri %50 daha büyük olacaktır",
    datedisplayformat: "Tarih görüntüleme formatı",
    containsWord: "İçerir kullanarak yapılan dize araması, sorgudaki her kelimeyi ayrı ayrı arayacaktır.",
    containsWordExample: "Örneğin: \"John Doe\" ifadesi, Üst(Name) LIKE '\%John\%' VE Üst(Name) LIKE '\%Doe\%' SQL ifadesine sahip olacak ve varsayılan olarak Üst(Name) LIKE '\%John Doe\%' yerine geçecektir.",
    listInteract: "Fareyle üzerine gelindiğinde arama sonucunu vurgula",
    attchmentView: "Ek bağlantılarını göster",
    attchViewText: "Metin Bağlantısı",
    attachViewImage: "Resim\\Simge Bağlantısı"
});