name: Generate LLMS.txt

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  generate-llms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Install dependencies
        run: |
          gem install jekyll
          bundle install
          
      - name: Generate llms.txt
        run: |
          ruby -e '
            require "yaml"
            require "fileutils"
            
            config = YAML.load_file("_config.yml")
            site_url = config["url"]
            
            posts = Dir.glob("_posts/**/*.md").map do |post_file|
              content = File.read(post_file)
              front_matter = YAML.load(content.split("---")[1])
              {
                title: front_matter["title"],
                date: front_matter["date"],
                url: "/#{post_file.gsub("_posts/", "").gsub(".md", "")}",
                excerpt: front_matter["excerpt"] || front_matter["description"] || content.split("---")[2].strip[0..200] + "..."
              }
            end.sort_by { |post| post[:date] }.reverse
            
            content = <<~MARKDOWN
              # Mert Turunç\'s Blog
              
              ## About
              This is a personal blog and portfolio website showcasing projects, blog posts, and professional information about Mert Turunç.
              
              ## Main Content
              The site contains the following main sections:
              - Blog posts about technology, programming, and personal experiences
              - Project showcases and descriptions
              - Professional information and resume
              - Technical articles and tutorials
              
              ## Important Pages
              - Homepage: #{site_url}
              - Blog: #{site_url}/blog/
              - Projects: #{site_url}/projects/
              
              ## Blog Posts
              #{posts.map { |post| 
                "- [#{post[:title]}](#{site_url}#{post[:url]}) - #{post[:date].strftime("%Y-%m-%d")}\n  #{post[:excerpt]}"
              }.join("\n\n")}
              
              ## Content Guidelines
              - All blog posts are written in either Turkish or English
              - Technical content focuses on programming, web development, and technology
              - Project descriptions include implementation details and technologies used
              
              ## Last Updated
              Generated at: #{Time.now.strftime("%Y-%m-%d %H:%M:%S UTC")}
              
              ## Additional Information
              This file is automatically generated during the build process to help AI models better understand and process the website\'s content.
            MARKDOWN
            
            File.write(File.join("_site", "llms.txt"), content)
            puts "Generated llms.txt in _site directory"
          '
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site 